# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

ZOOKEEPER_HOSTS = 3
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    (1..ZOOKEEPER_HOSTS).each do |i|
        config.vm.define "zk#{i}" do |zk|
            zk.ssh.forward_agent = true
            zk.vm.box = "chef/fedora-20"
            zk.vm.box_check_update = false
            zk.vm.hostname = "zk#{i}"
            zk.vm.network "private_network", ip: "192.168.33.#{i + 50}"
            zk.vm.synced_folder "./", "/vagrant", disabled: true
            zk.vm.synced_folder "pkg/", "/tmp/pkg", create: true, mount_options: ["ro",]
            zk.vm.provider "virtualbox" do |vb|
                vb.customize ["modifyvm", :id, "--memory", "1024"]
            end

            zk.vm.provision "shell", inline: "echo export SEQUENCE_ID=$1 >> /etc/profile.d/vagrant.sh", args: ["#{i}"]
            zk.vm.provision "shell", path: "provision.sh"
        end
    end
end
